/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
        "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    safelist: [
        "group-hover:bg-blue-700/80",
        "group-hover:bg-purple-700/80",
        "group-hover:bg-green-700/80",
        "group-hover:bg-pink-700/80",
        "group-hover:bg-yellow-700/80",
        "group-hover:bg-cyan-700/80",
        "from-blue-900/8",
        "to-gray-900/50",
        "hover:from-blue-800/12",
        "hover:to-gray-800/40",
        "from-purple-900/8",
        "hover:from-purple-800/12",
        "from-green-900/8",
        "hover:from-green-800/12",
        "from-pink-900/8",
        "hover:from-pink-800/12",
        "from-yellow-900/8",
        "hover:from-yellow-800/12",
        "from-cyan-900/8",
        "hover:from-cyan-800/12",
        "skill-animate-rotate",
        "skill-animate-bounce",
        "skill-animate-scale",
        "skill-animate-pulse",
        "skill-animate-wiggle",
        "skill-animate-float",
        // Button gradient classes
        "bg-gradient-to-r",
        "from-blue-600",
        "to-blue-700",
        "hover:from-blue-700",
        "hover:to-blue-800",
        "from-gray-700",
        "to-gray-800",
        "hover:from-gray-600",
        "hover:to-gray-700",
        // Button shadow classes
        "shadow-md",
        "hover:shadow-lg",
        // Button border classes
        "border-blue-500/30",
        "hover:border-blue-400/50",
        "border-gray-600/30",
        "hover:border-gray-500/50",
        // Skill icon border classes
        "border-gray-600/30",
        "hover:border-gray-500/50",
        // Footer link classes
        "text-blue-400",
        "hover:text-blue-300",
        "text-cyan-400",
        "hover:text-cyan-300",
        "decoration-blue-500/50",
        "hover:decoration-blue-400/70",
        "decoration-cyan-500/50",
        "hover:decoration-cyan-400/70",
        // Footer gradient classes
        "bg-gradient-to-r",
        "from-transparent",
        "to-gray-600",
        "bg-gradient-to-l",
        "from-gray-600",
        "bg-blue-600/50",
        "via-cyan-600/50",
        "to-blue-600/50",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ["var(--font-space-grotesk)", "system-ui", "sans-serif"],
                heading: ["var(--font-inter)", "system-ui", "sans-serif"],
                mono: ["var(--font-jetbrains-mono)", "monospace"],
            },
        },
    },
    plugins: [],
};
