/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'group-hover:bg-blue-700/80',
    'group-hover:bg-purple-700/80',
    'group-hover:bg-green-700/80',
    'group-hover:bg-pink-700/80',
    'group-hover:bg-yellow-700/80',
    'group-hover:bg-cyan-700/80',
    'from-blue-900/8',
    'to-gray-900/50',
    'hover:from-blue-800/12',
    'hover:to-gray-800/40',
    'from-purple-900/8',
    'hover:from-purple-800/12',
    'from-green-900/8',
    'hover:from-green-800/12',
    'from-pink-900/8',
    'hover:from-pink-800/12',
    'from-yellow-900/8',
    'hover:from-yellow-800/12',
    'from-cyan-900/8',
    'hover:from-cyan-800/12',
    'skill-animate-rotate',
    'skill-animate-bounce',
    'skill-animate-scale',
    'skill-animate-pulse',
    'skill-animate-wiggle',
    'skill-animate-float',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'monospace'],
      },
    },
  },
  plugins: [],
}
